config/routes.rb
Blog::Application.routes.draw do
  match "about" => "pages#about", :as => "about"

  devise_for :users

  resources :posts
  root :to => 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


    unless user
      can :read, :all
    else
    	can :create, Post
    	can :manage, Post do |p|
    		p.try(:user) == user 
    	end 

		can :read, :all
		if user.is_admin?
			can :manage, :all
		end
    
	end
  end
end

 

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name
  validates :name, :uniqueness => :true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :genre
  belongs_to :user
  attr_accessible :content, :title, :created_at, :link, :genre_id, :image, :user_id


 
  has_attached_file :image, :styles => { :thumb => "200x200"}

	validates_attachment_presence :image
	validates_attachment_size :image, :less_than => 5.megabytes
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png', 'image/jpg']

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin, :post_ids
  # attr_accessible :title, :body

  def is_admin?
  	self.admin

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post, root: false }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="#">Sarasvatī</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><%= link_to "Accueil", root_path %></li>
          <li><%= link_to "Rapport", about_path %></li>
        </ul>
        <% if user_signed_in? %>
        <p class="navbar-text pull-right">
            Connecté en tant que <%= current_user.email %>.
            <%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %>
        </p>
        <% else %> 
          <%= form_for("user", :url => user_session_path, html: {class: 'navbar-form pull-right'}) do |f| %>
            <%= f.text_field :email, placeholder: 'Email', class: 'span2' %>
            <%= f.password_field :password, placeholder: 'Mot-de-passe', class: 'span2' %>
            <%= f.submit 'Sign in', class: 'btn' %>
            <%= link_to "Sign up", new_user_registration_path, class: 'btn' %>              
          <% end %>

        <% end %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container main-container">
  <!-- Affichage des messages -->
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="banniere">
  <img classe="imgban" src="assets/logocraki.png">
</div>
<h1>Rapport</h1>
<hr/>
<p>
	Notre projet est la réalisation d'un site web. Il s'agit d'un blog de partage de musique où les utilisateurs auront la possibilité d'ajouter, d'éditer ou de supprimer leurs propres données. 
	Seul l'administrateur aura les droits pour accéder et modifier l'intégralité des données.
</p>
<hr/>
<p>
	<b>Le Framework :</b><br/>
	Pour ce projet nous avons décidé d'utiliser Ruby and Rails, un framework libre qui suit le motif de conception Modèle-Vue-Contrôleur. Nous l'avons choisi car il s'agit d'une façon moderne de programmer.De plus la communauté Ruby est trés développée sur internet (<a href="http://guides.rubyonrails.org/">rubyguide</a> et <a href="http://railscasts.com/">railscasts</a>).
</p>
<hr/>
<p>
	<b>Les modèles:</b><br/>
	Un modèle représente l’information, les données d’une application et les règles pour la manipuler. Sur notre site, nous avons quatre modèles.<br/>
	-Post : Il s'agit de notre modéle principale.<br/>
	-Genre : Ce modèle contient juste un nom et un id.<br/>
	-User : Ce modèle contient toutes les données utiles sur les utilisateurs.<br/>
	Ces trois modéles correspondent à nos trois tables présentes dans notre base de données. Elles sont reliés par des relations logiques : "Post belongs_to user and genre" et "User has_many posts".<br/>
	<br/>
	Nous avons aussi un modèle ability qui définit les droits des users.
</p>
<p>
	<b>Les contrôleurs :</b><br/>
	D'aprés railsguide : "Les contrôleurs constituent la “colle” entre les modèles et les vues. En Rails, les contrôleurs sont responsables du traitement des requêtes entrantes en provenance du navigateur, de l’interrogation des modèles pour obtenir des données, et du passage de ces données aux vues pour leur présentation."<br/>
	Ici, ce qu'il est important de comprendre, c'est le posts_controlleur. Le traitement se fait de cette façon :
<TABLE BORDER="1"> 
	<TR> 
 		<TH> Http method </TH> 
		<TH> path </TH> 
	 	<TH> action </TH> 
 		<TH> used for </TH> 
	</TR> 
	<TR> 
		<TH> GET </TH> 
 		<TD> /posts </TD> 
 		<TD> index </TD> 
 		<TD> display a list of all posts </TD> 
  	</TR>
  	<TR> 
 		<TH> GET </TH> 
 		<TD> /posts/new </TD> 
 		<TD> new </TD> 
 		<TD> return an html form for creating a new post </TD> 
	</TR>
  	<TR> 
 		<TH> POST </TH> 
 		<TD> /posts </TD> 
 		<TD> create </TD> 
 		<TD> create a new photo </TD> 
	</TR> 
  	<TR> 
 		<TH> GET </TH> 
 		<TD> /posts/:id </TD> 
 		<TD> show </TD> 
 		<TD> display a specific post </TD> 
	</TR>
  	<TR> 
 		<TH> GET </TH> 
 		<TD> /posts/:id/edit </TD>
 		<TD> edit </TD> 
 		<TD> return an html form for editing a post </TD> 
	</TR>
  	<TR> 
 		<TH> PUT </TH> 
 		<TD> /posts/:id </TD> 
 		<TD> update </TD> 
 		<TD> update a specific post </TD> 
	</TR>
  	<TR> 
 		<TH> DELETE </TH> 
 		<TD> /posts/:id </TD> 
 		<TD> destroy </TD> 
 		<TD> delete a specific post </TD> 
	</TR> 

</TABLE> 
</p>
<p>
	<b>Les vues : </b><br/>
	Les vues sont les interfaces "Utilisateur" de l'application. Les vues sont des fichiers HTML contenant du code Ruby intégré.<br/>
	La vue application.html.erb présente dans views/layouts est la vue principale appelée sur toutes les pages du site web. Dans cette vue, on appelle la fonction yield, qui va afficher la vue secondaire que le contrôlleur va lui indiquer.<br/>
	Nous avons des vues secondaires qui correspondent aux edit, index, new et show pour le contrôlleur posts. Ainsi que la vue about, page où vous vous trouvez actuellement.
</p>
<hr/>
<p>
	<b>Schéma de la base :</b><br/>
	Table Post :<br/>
	<img classe="imgban" src="assets/tablepost.png">
	<br/>
	Table User :<br/>
	<img classe="imgban" src="assets/tableuser.png">
	<br/>
	Table genre :<br/>
	<img classe="imgban" src="assets/tablegenre.png">
	<br/>
</p>
<hr/>
<p>
	<b>CSS et Javascript : </b><br/>
	Nous n'avons pas beaucoup modifié le CSS (app/assets/stylesgeets/post.css.scss). En effet, le gros du travail du design a été réalisé grâce à boostrap, une bibliothèque css et javascript. Par exemple, nous avons pu créer la barre de navigation et les boutons. Mais le plus intéressant a été l'utilisation du "default grip système" qui permet de diviser l'écran en 12 colonnes, et d'y insérer nos éléments. L'intêret de ce système est qu'il est 'responsive', c'est-à-dire qu'il s'adapte à l'écran.<br/>
	<br/>
	Nous avons utilisé deux scipts javascript : mustach et fitvid (pour rendre la video responsive).<br/>
	<br/>
	Nous avons aussi réalisé un script en coffeescript pour réaliser différentes actions sur les vues du post. On le retrouve dans app/assets/javascript/posts.js.coffe.	
</p>
<hr/>
<p>
	<b>Les gems :</b><br/>
	Nous avons choisi d'utiliser ruby and rails pour son systéme de gem trés pratique (voir dans vendor/gemfile). Il s'agit d'une bibliothèque libre qui est réalisée de façon contributive par des développeurs.<br/>
	Nous avons utilisé : <br/>
	-devise<br/>
	-cancan<br/>
	-paperclip<br/>
	-active_model_serializers<br/>
	-bootstrap<br/>
</p>
<hr/>
<p>
	<b>Annexe volumétrique des étapes :</b><br/>
	Nous nous sommes organiser de façon simple. La premiére séance nous avons découvert le sujet, découvert les téchnologies éxistantes. C'est aprés la premiére séance que nous avons choisie d'utiliser ruby and rails. La seconde séance nous nous sommes créer un compte github, qui nous a permit par la suite une bonne organisation. En effet nous avons beacoup travaillé chez nous (tout seul ou à plusieurs), nous semblions etre plus éfficace. Ce github nous a permis de mettre à jours le projet à chaque fois que quelqu'un fesait une modification. Nous avons séparer le travail en deux grandes parties d'un côté le dévellopement et de l'autre la configguration du serveur apache et de la BDD MySql.
	
</p>
<hr/>
<p>
	<b>Sécurité :</b><br/>
	Le site semble plutôt sécurisé, on ne peut accéder aux fonctions edit ou destroy sans les droits aproprié. La seul faille de sécurité potentiel (que nous avons repéré), est l'authentification.
</p>
<hr/>
<p>
	<b>optimisation pour le référencement :</b><br/>
	Nous avons appris lors du projets, que ruby and rails pérmétait une obtimisation du sit pour le référencement, en particulier en ce qui concerne l'organisations des urls. Dans le même but nous avons garder la view show qui semble inutile puisqu'on affiche les posts en java. Mais ils sont tout de même utiles, car le référencement ne prend pas en compte le contenue présent dans le java.

</p>
<br/>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br />
    <%= f.select(:genre_id, Genre.all.map {|r| [r.name,r.id] }) %>
  </div>
  <div classe="image">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>And her Dope Tunes</h1>
<div class="banniere">
  <img classe="imgban" src="assets/logocraki.png">
</div>
<div id="display-post" ></div>


<table id="posts">

  <!-- Selection du genre -->
  <ul class="nav nav-pills" id="gender-filter">
    <li class="active", data-active-id = '0' >
      <a class = 'genre', data-click-id = '0' >Tout</a>
    </li>
    <% Genre.all.each do |g| %>
      <li data-active-id = '<%= g.id %>'>
        <a class = 'genre', data-click-id = '<%= g.id %>' >
           <%= g.name %> : <%= Post.where(genre_id: g.id).count() %>
        </a>
      </li>
    <% end %>
  </ul>

  <!-- Affichage des postes -->
  <div class="row">
    <% @posts.each do |post| %>
      <div class="span3 post" data-genre-id = '<%= post.genre_id %>' >
          <%= link_to "#", class: "post-link", data: {:json => post_path( id: post.id, format: :json )} do %>
            <%= image_tag post.image.url, class: "img-rounded" %>
          <% end %>
      </div>
   <% end %>
  </div>

</table>

<br />
<% if user_signed_in? %>
<%= link_to 'New Post', new_post_path %>
<%  end %>

<script id="post-template" type="text/template">
<div class="row rowtemplate">
  <div class="span6">
    <div class="fluid-width-video-wrapper">
      <iframe width="560" height="315" src="http://www.youtube.com/embed/{{ link }}" frameborder="0" allowfullscreen></iframe>
    </div>
  </div>


  <div class=" span6">
    <p class="next_prev_buttons">
      <a href="#" class="post-link" data-json="/posts/{{next_post}}.json"><i class="icon-fast-forward"></i></a>
      {{#autorized}}
        <a href="posts/{{id}}/edit" >Edit</a>
      {{/autorized}}

      <a href="#" class="post-link" data-json="/posts/{{prev_post}}.json"><i class="icon-fast-backward"></i></a>
    </p>
    <div class="ligne"></div>

    <h2>{{ title }}</h2>
    <div class="ligne"></div>

    <b>Categorie : </b>{{  genre }}
    <div class="ligne"></div>

    <b>Content : </b>{{ content }}

  </div>
</div>

<div class="ligne"><img classe="imgligne" src="assets/cd.png"></div>
</script>

app/views/posts/new.html.erb
<h1>Ajout d'un post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
  

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
<%= image_tag @post.image.url %>
<p>
	<b>Genre: </b>
	<%= @post.genre.name %>

</p>
<p>
  <b>Vidéo:</b>
      <div class="fluid-width-video-wrapper">
  <%= @post.link %>
  <iframe width="560" height="315" src="http://www.youtube.com/embed/<%= @post.link %>" frameborder="0" allowfullscreen></iframe>
</div>
</p>
<p>
	<b>email du posteur : <b/>
  <%= @post.user.email %>

</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>